using System;
using System.Collections.Generic;
using System.Linq;
using ArtificialVCM.Configuration;
using Common.Entities;
using Common.Exceptions;
using Common.Helpers;
using Common.Randoms;

namespace ArtificialVCM
{
    public sealed class ArtificialVCMAgent : Agent
    {
        public AgentStateConfiguration AgentStateConfiguration { get; private set; }

        public override Agent Clone()
        {
            ArtificialVCMAgent agent = (ArtificialVCMAgent)base.Clone();

            return agent;
        }

        public void GenerateCustomParams()
        {

        }

        /// <summary>
        /// Creates agent instance based on agent prototype and agent configuration 
        /// </summary>
        /// <param name="agentConfiguration"></param>
        /// <param name="prototype"></param>
        /// <returns></returns>
        public static ArtificialVCMAgent CreateAgent(AgentStateConfiguration agentConfiguration, AgentPrototype prototype)
        {
            ArtificialVCMAgent agent = new ArtificialVCMAgent();

            agent.Prototype = prototype;
            agent.privateVariables = new Dictionary<string, dynamic>(agentConfiguration.PrivateVariables);

            agent.AssignedKnowledgeHeuristics = prototype.KnowledgeHeuristics.Where(r => agentConfiguration.AssignedKnowledgeHeuristics.Contains(r.Id)).ToList();
            agent.AssignedGoals = prototype.Goals.Where(g => agentConfiguration.AssignedGoals.Contains(g.Name)).ToList();

            agent.AssignedKnowledgeHeuristics.ForEach(kh => agent.KnowledgeHeuristicActivationFreshness.Add(kh, 1));

            //generate goal importance
            agentConfiguration.GoalsState.ForEach(kvp =>
            {
                var goalName = kvp.Key;
                var configuration = kvp.Value;

                var goal = agent.AssignedGoals.FirstOrDefault(g => g.Name == goalName);
                if (goal == null) return;

                double importance = configuration.Importance;

                if (configuration.Randomness)
                {
                    if (string.IsNullOrEmpty(configuration.BasedOn))
                    {
                        var from = (int)(configuration.RandomFrom * 10);
                        var to = (int)(configuration.RandomTo * 10);

                        importance = Math.Round(LinearUniformRandom.GetInstance.Next(from, to + 1) * 0.1, 2);
                    }
                    else
                    {
                        var from = (int)(configuration.RandomFrom * 10);
                        var to = 10 - (int)(agent
                            .GoalStates[agent.AssignedGoals.FirstOrDefault(g => g.Name == configuration.BasedOn)]
                            .Importance * 10);

                        importance = Math.Round(LinearUniformRandom.GetInstance.Next(from, to + 1) * 0.1, 2);
                    }
                }

                GoalState goalState = new GoalState(configuration.Value, goal.FocalValue, importance);

                agent.GoalStates.Add(goal, goalState);

                agent[string.Format("{0}_Importance", goal.Name)] = importance;
            });

            //initializes initial anticipated influence for each kh and goal assigned to the agent
            agent.AssignedKnowledgeHeuristics.ForEach(kh =>
            {
                Dictionary<string, double> source;

                if (kh.AutoGenerated && agent.Prototype.DoNothingAnticipatedInfluence != null)
                {
                    source = agent.Prototype.DoNothingAnticipatedInfluence;
                }
                else
                {
                    agentConfiguration.AnticipatedInfluenceState.TryGetValue(kh.Id, out source);
                }


                Dictionary<Goal, double> inner = new Dictionary<Goal, double>();

                agent.AssignedGoals.ForEach(g =>
                {
                    inner.Add(g, source != null && source.ContainsKey(g.Name) ? source[g.Name] : 0);
                });

                agent.AnticipationInfluence.Add(kh, inner);
            });


            //applying transforms
            if (agentConfiguration.VariablesTransform != null)
            {
                agentConfiguration.VariablesTransform.ForEach(kvp =>
                {
                    var variable = kvp.Key;
                    var reference = kvp.Value;

                    switch (reference)
                    {
                        case AlgorithmVariables.G1Importance:
                            {
                                agent[variable] = agent[AlgorithmVariables.G1Importance] * 10;
                                break;
                            }
                        case AlgorithmVariables.G2Importance:
                            {
                                agent[variable] = agent[AlgorithmVariables.G2Importance] * 10;
                                break;
                            }

                        default:
                            throw new UnknownVariableException(reference);
                    }
                });
            }

            if (agentConfiguration.AnticipatedInfluenceTransform != null)
            {
                agentConfiguration.AnticipatedInfluenceTransform.ForEach(kvp =>
                {
                    var heuristic = agent.AssignedKnowledgeHeuristics.FirstOrDefault(kh => kh.Id == kvp.Key);

                    kvp.Value.ForEach(goalsInfluence =>
                    {
                        var goal = agent.AssignedGoals.FirstOrDefault(g => g.Name == goalsInfluence.Key);
                        agent.AnticipationInfluence[heuristic][goal] = agent[goalsInfluence.Value];
                    });
                });
            }

            agent.AgentStateConfiguration = agentConfiguration;

            return agent;
        }
    }
}
